/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graficos;

import Actividades.AgenteP;
import Actividades.Bailar;
import Actividades.Correr;
import Actividades.Diversion;
import Actividades.Dormir;
import Actividades.Ejercicio;
import Alimentación.Algas;
import Alimentación.Camarones;
import Alimentación.Moluzcos;
import Alimentación.Pez;
import Alimentación.Renacuajos;
import java.awt.event.ActionEvent;
import java.util.TimerTask;
import java.util.Timer;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import tamagotchi.Cronometro;
import tamagotchi.Ornitorrinco;
import Medicina.Medicamento;

/**
 *
 * @author joans
 */
public class JuegoPrincipal extends javax.swing.JFrame {

    //BTN MEDICINA
    Medicamento med;
    int seg;
//ATRIBUTOS------------------------------------

    private int contadorDías;
    private String Nombre;
    Cronometro cron;
    static int cont = 0;//ES PARA BOTONES
    static int conte = 0;//ES PARA MOSTRAR LAS EDADES
    static int conta = 0;//ES PARA MOSTRAR LAS EDADES
    static int contaS = 0;//ES PARA MOSTRAR LAS EDADES
    static int contaSa = 0;//ES PARA MOSTRAR LAS ACTIVIDADES RECREATIVAS
    static int contadorBaño = 0;//ES PARA MOSTRAR LAS LA NECESIDAD DE IR AL BAÑO
//OBJECTOS-------------------------------------
    Ornitorrinco or = new Ornitorrinco(Nombre);
    Camarones cam = new Camarones();
    Renacuajos ren = new Renacuajos();
    Algas al = new Algas();
    Moluzcos mol = new Moluzcos();
    Pez pez = new Pez();
    Bailar ba = new Bailar();
    Correr co = new Correr();
    Diversion di = new Diversion();
    Ejercicio ej = new Ejercicio();
    AgenteP agen = new AgenteP();
    Dormir dor=new Dormir();
   Medicamento medi=new Medicamento();

//---------------------------------------------
    /**
     * Creates new form JuegoPrincipal
     */
    public JuegoPrincipal() {
        initComponents();
        deshabilitarBotones();
        MostrarDiaNoche(this.fondoDia, this.fondoNoche); // Esto hace un cambio de dia a noche y viceversa
        barrasBar();
        cron = new Cronometro();
        timer.start();
        this.btnNecesidad.setVisible(false);

    }
    javax.swing.Timer timer = new javax.swing.Timer(1000, (ActionEvent e) -> {
        //this.tiempo.setText(cron.toString());
        this.cron.contar();
    });

    private void barrasBar() {
        this.pAburrimiento.setValue(or.getAburrimiento());
        this.pEnergía.setValue(or.getEnergía());
        this.pHambre.setValue(or.getHambre());
        this.pNecesidad.setValue(or.getNecesidad());

    }

    private void deshabilitarBotones() {
        this.btnAlgas.setEnabled(false);
        this.btnCamarones.setEnabled(false);
        this.btnMoluzco.setEnabled(false);
        this.btnPez.setEnabled(false);
        this.btnRenacuajo.setEnabled(false);
        this.btnAgenteP.setEnabled(false);
        this.btnBailar.setEnabled(false);
        this.btnCorrer.setEnabled(false);
        this.btnDivertirse.setEnabled(false);
        this.btnEjercicio.setEnabled(false);
        //-------------------------jlabel-----------------------
        this.Bebe.setVisible(false);
        this.Joven.setVisible(false);
        this.JEnfermo.setVisible(false);
        this.PBailando.setVisible(false);
        this.PAgenteP.setVisible(false);
        this.PCorriendo.setVisible(false);
        this.PDivertirse.setVisible(false);
        this.PEjercicio.setVisible(false);
    }

    private void habilitarBotones(int contadorDías) {
        if (contadorDías == 3) {
            this.btnCamarones.setEnabled(true);
            this.btnBailar.setEnabled(true);

        }
        if (contadorDías == 5) {
            this.btnRenacuajo.setEnabled(true);
            this.btnCorrer.setEnabled(true);
        }
        if (contadorDías == 7) {
            this.btnAlgas.setEnabled(true);
            this.btnDivertirse.setEnabled(true);
            this.btnAgenteP.setEnabled(true);
        }
        if (contadorDías == 10) {
            this.btnMoluzco.setEnabled(true);
            this.btnEjercicio.setEnabled(true);
        }
        if (contadorDías == 12) {
            this.btnPez.setEnabled(true);
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pNecesidad = new javax.swing.JProgressBar();
        btnNecesidad = new javax.swing.JButton();
        btnDormir = new javax.swing.JButton();
        btnMedicamento = new javax.swing.JButton();
        btnBailar = new javax.swing.JButton();
        btnCorrer = new javax.swing.JButton();
        btnDivertirse = new javax.swing.JButton();
        btnEjercicio = new javax.swing.JButton();
        btnAgenteP = new javax.swing.JButton();
        JEnfermo = new javax.swing.JLabel();
        Joven = new javax.swing.JLabel();
        tEdad = new javax.swing.JLabel();
        Bebe = new javax.swing.JLabel();
        btnCamarones = new javax.swing.JButton();
        btnRenacuajo = new javax.swing.JButton();
        btnAlgas = new javax.swing.JButton();
        btnMoluzco = new javax.swing.JButton();
        btnPez = new javax.swing.JButton();
        pHambre = new javax.swing.JProgressBar();
        pEnergía = new javax.swing.JProgressBar();
        pAburrimiento = new javax.swing.JProgressBar();
        Brilo = new javax.swing.JLabel();
        Huevo = new javax.swing.JLabel();
        fondoDia = new javax.swing.JLabel();
        fondoNoche = new javax.swing.JLabel();
        PCorriendo = new javax.swing.JLabel();
        PDivertirse = new javax.swing.JLabel();
        PDurmiendo = new javax.swing.JLabel();
        PBailando = new javax.swing.JLabel();
        PEjercicio = new javax.swing.JLabel();
        PAgenteP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pNecesidad.setBackground(new java.awt.Color(51, 255, 51));
        pNecesidad.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pNecesidad.setForeground(new java.awt.Color(255, 255, 255));
        pNecesidad.setToolTipText("");
        pNecesidad.setString("NECESIDAD");
        pNecesidad.setStringPainted(true);
        jPanel1.add(pNecesidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 170, 20));

        btnNecesidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CACABT1.png"))); // NOI18N
        btnNecesidad.setContentAreaFilled(false);
        btnNecesidad.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CACABT2.png"))); // NOI18N
        btnNecesidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNecesidadActionPerformed(evt);
            }
        });
        jPanel1.add(btnNecesidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, -1, -1));

        btnDormir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DORMIRBT1.png"))); // NOI18N
        btnDormir.setContentAreaFilled(false);
        btnDormir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DORMIRBT2.png"))); // NOI18N
        btnDormir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDormirActionPerformed(evt);
            }
        });
        jPanel1.add(btnDormir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, -1, -1));

        btnMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MEDICAMENTOBTN1.png"))); // NOI18N
        btnMedicamento.setContentAreaFilled(false);
        btnMedicamento.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MEDICAMENTOBTN2.png"))); // NOI18N
        btnMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        btnBailar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BAILARBTN1.png"))); // NOI18N
        btnBailar.setContentAreaFilled(false);
        btnBailar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BAILARBTN2.png"))); // NOI18N
        btnBailar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBailarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBailar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 160, -1, -1));

        btnCorrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CORRERBTN1.png"))); // NOI18N
        btnCorrer.setContentAreaFilled(false);
        btnCorrer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CORRERBTN2.png"))); // NOI18N
        btnCorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrerActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 260, -1, -1));

        btnDivertirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DIVERTIRSEBTN1.png"))); // NOI18N
        btnDivertirse.setContentAreaFilled(false);
        btnDivertirse.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DIVERTIRSEBTN2.png"))); // NOI18N
        btnDivertirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivertirseActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivertirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 360, -1, -1));

        btnEjercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EJERCICIOBT1.png"))); // NOI18N
        btnEjercicio.setContentAreaFilled(false);
        btnEjercicio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EJERCICIOBTN2.png"))); // NOI18N
        btnEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjercicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnEjercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 460, -1, -1));

        btnAgenteP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AGENTEBTN1.png"))); // NOI18N
        btnAgenteP.setContentAreaFilled(false);
        btnAgenteP.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AGENTEBTN2.png"))); // NOI18N
        btnAgenteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentePActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgenteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 560, -1, -1));

        JEnfermo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/termometro (1).gif"))); // NOI18N
        jPanel1.add(JEnfermo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 190, 400));

        Joven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Joven.gif"))); // NOI18N
        jPanel1.add(Joven, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 730, 350));

        tEdad.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jPanel1.add(tEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        Bebe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebe (1).gif"))); // NOI18N
        jPanel1.add(Bebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 550, 430));

        btnCamarones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camarones.png"))); // NOI18N
        btnCamarones.setContentAreaFilled(false);
        btnCamarones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamaronesActionPerformed(evt);
            }
        });
        jPanel1.add(btnCamarones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        btnRenacuajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/renacuajo.png"))); // NOI18N
        btnRenacuajo.setContentAreaFilled(false);
        btnRenacuajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenacuajoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRenacuajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        btnAlgas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/algas.png"))); // NOI18N
        btnAlgas.setContentAreaFilled(false);
        btnAlgas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlgasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlgas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        btnMoluzco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moluzcos.png"))); // NOI18N
        btnMoluzco.setContentAreaFilled(false);
        btnMoluzco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoluzcoActionPerformed(evt);
            }
        });
        jPanel1.add(btnMoluzco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        btnPez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pez.png"))); // NOI18N
        btnPez.setContentAreaFilled(false);
        btnPez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPezActionPerformed(evt);
            }
        });
        jPanel1.add(btnPez, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        pHambre.setBackground(new java.awt.Color(51, 255, 51));
        pHambre.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pHambre.setForeground(new java.awt.Color(255, 255, 255));
        pHambre.setToolTipText("");
        pHambre.setString("HAMBRE");
        pHambre.setStringPainted(true);
        jPanel1.add(pHambre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 170, 20));

        pEnergía.setBackground(new java.awt.Color(51, 255, 51));
        pEnergía.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pEnergía.setForeground(new java.awt.Color(255, 255, 255));
        pEnergía.setToolTipText("");
        pEnergía.setString("ENERGÍA");
        pEnergía.setStringPainted(true);
        jPanel1.add(pEnergía, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 170, 20));

        pAburrimiento.setBackground(new java.awt.Color(51, 255, 51));
        pAburrimiento.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pAburrimiento.setForeground(new java.awt.Color(255, 255, 255));
        pAburrimiento.setToolTipText("");
        pAburrimiento.setString("ABURRIMIENTO");
        pAburrimiento.setStringPainted(true);
        jPanel1.add(pAburrimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 170, 20));

        Brilo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/brillo.gif"))); // NOI18N
        jPanel1.add(Brilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 370, 360));

        Huevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huevo.png"))); // NOI18N
        jPanel1.add(Huevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 380, 360));

        fondoDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(fondoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        fondoNoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo4.jpg"))); // NOI18N
        jPanel1.add(fondoNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        PCorriendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PerryCorriendo.gif"))); // NOI18N
        jPanel1.add(PCorriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        PDivertirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PerryDivertiendose.gif"))); // NOI18N
        jPanel1.add(PDivertirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1280, 720));

        PDurmiendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perryDurmiendoo.png"))); // NOI18N
        jPanel1.add(PDurmiendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1280, 720));

        PBailando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PerryBailando.gif"))); // NOI18N
        jPanel1.add(PBailando, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PEjercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PerryEjercicio.gif"))); // NOI18N
        jPanel1.add(PEjercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1280, 720));

        PAgenteP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PAgenteP.gif"))); // NOI18N
        jPanel1.add(PAgenteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCamaronesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamaronesActionPerformed
///OCULTA EL BOTON DE CAMARONES
        or.quitarHambre(cam.getCantidadDeAlimentación());
        cam.tiempoOcultar(this.btnCamarones, cam.getTiempo());
        or.subirEnergía(cam.getEnergia());
        barrasBar();


    }//GEN-LAST:event_btnCamaronesActionPerformed

    private void btnRenacuajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenacuajoActionPerformed
        or.setHambre(ren.getCantidadDeAlimentación());
        ren.tiempoOcultar(this.btnRenacuajo, ren.getTiempo());
        or.subirEnergía(ren.getEnergia());
        barrasBar();
    }//GEN-LAST:event_btnRenacuajoActionPerformed

    private void btnAlgasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlgasActionPerformed

        or.quitarHambre(al.getCantidadDeAlimentación());
        al.tiempoOcultar(btnPez, al.getTiempo());
        or.subirEnergía(al.getEnergia());
        barrasBar();
    }//GEN-LAST:event_btnAlgasActionPerformed

    private void btnMoluzcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoluzcoActionPerformed
        or.quitarHambre(mol.getCantidadDeAlimentación());
        mol.tiempoOcultar(this.btnMoluzco, mol.getTiempo());
        or.subirEnergía(mol.getEnergia());
        barrasBar();
    }//GEN-LAST:event_btnMoluzcoActionPerformed

    private void btnPezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPezActionPerformed
        or.quitarHambre(pez.getCantidadDeAlimentación());
        or.subirEnergía(pez.getEnergia());
        pez.tiempoOcultar(this.btnPez, pez.getTiempo());
        barrasBar();

    }//GEN-LAST:event_btnPezActionPerformed

    private void btnBailarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBailarActionPerformed

        ba.tiempoOcultar(this.btnBailar, ba.getTiempo());
        or.setEnergía(ba.getEnergía());
        or.bajarAburrimiento(ba.getAburrimiento());
        tiempoOcultarA(this.PBailando, 5);
        barrasBar();

    }//GEN-LAST:event_btnBailarActionPerformed

    private void btnCorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrerActionPerformed
      
        co.tiempoOcultar(this.btnCorrer, co.getTiempo());
        or.setEnergía(co.getEnergía());
        or.bajarAburrimiento(co.getAburrimiento());
        tiempoOcultarA(this.PCorriendo, 5);
        barrasBar();
    }//GEN-LAST:event_btnCorrerActionPerformed

    private void btnDivertirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivertirseActionPerformed

        di.tiempoOcultar(this.btnDivertirse, di.getTiempo());
        or.setEnergía(di.getEnergía());
        or.bajarAburrimiento(di.getAburrimiento());
        tiempoOcultarA(this.PDivertirse, 5);
        barrasBar();
    }//GEN-LAST:event_btnDivertirseActionPerformed

    private void btnEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjercicioActionPerformed
     
        ej.tiempoOcultar(this.btnEjercicio, ej.getTiempo());
        or.setEnergía(ej.getEnergía());
        or.bajarAburrimiento(ej.getAburrimiento());
        tiempoOcultarA(this.PEjercicio, 5);
        barrasBar();
    }//GEN-LAST:event_btnEjercicioActionPerformed

    private void btnAgentePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentePActionPerformed

        agen.tiempoOcultar(this.btnAgenteP, agen.getTiempo());
        or.setEnergía(agen.getEnergía());
        or.bajarAburrimiento(agen.getAburrimiento());
        tiempoOcultarA(this.PAgenteP, 8);
        barrasBar();
    }//GEN-LAST:event_btnAgentePActionPerformed

    private void btnMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentoActionPerformed
        efectoDeMedicamento();
        medi.tiempoOcultar(this.btnMedicamento, medi.getTiempo());
        barrasBar();

    }//GEN-LAST:event_btnMedicamentoActionPerformed

    private void btnDormirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDormirActionPerformed
    or.setEnergía(dor.getEnergia());
    dor.tiempoOcultar(this.btnDormir, dor.getTiempo());
    tiempoOcultarA(this.PDurmiendo,6);
    barrasBar();
    }//GEN-LAST:event_btnDormirActionPerformed

    private void btnNecesidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNecesidadActionPerformed
      or.bajarNecesidad();
      this.btnNecesidad.setVisible(false);
    }//GEN-LAST:event_btnNecesidadActionPerformed

    private void tiempoOcultarA(JLabel label, int time) {
        int tiempo = time * 1000;
        Timer timer;
        TimerTask timerTask;
        timerTask = new TimerTask() {

            @Override
            public void run() {
                switch (contaSa) {
                    case 0:
                        contaSa++;
                        label.setVisible(true);
                        break;
                    case 1:
                        contaSa = 0;
                        label.setVisible(false);
                        cancel();
                        break;

                }

            }

        };

        timer = new Timer();
        timer.schedule(timerTask, 0, tiempo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bebe;
    private javax.swing.JLabel Brilo;
    private javax.swing.JLabel Huevo;
    private javax.swing.JLabel JEnfermo;
    private javax.swing.JLabel Joven;
    private javax.swing.JLabel PAgenteP;
    private javax.swing.JLabel PBailando;
    private javax.swing.JLabel PCorriendo;
    private javax.swing.JLabel PDivertirse;
    private javax.swing.JLabel PDurmiendo;
    private javax.swing.JLabel PEjercicio;
    private javax.swing.JButton btnAgenteP;
    private javax.swing.JButton btnAlgas;
    private javax.swing.JButton btnBailar;
    private javax.swing.JButton btnCamarones;
    private javax.swing.JButton btnCorrer;
    private javax.swing.JButton btnDivertirse;
    private javax.swing.JButton btnDormir;
    private javax.swing.JButton btnEjercicio;
    private javax.swing.JButton btnMedicamento;
    private javax.swing.JButton btnMoluzco;
    private javax.swing.JButton btnNecesidad;
    private javax.swing.JButton btnPez;
    private javax.swing.JButton btnRenacuajo;
    private javax.swing.JLabel fondoDia;
    private javax.swing.JLabel fondoNoche;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar pAburrimiento;
    private javax.swing.JProgressBar pEnergía;
    private javax.swing.JProgressBar pHambre;
    private javax.swing.JProgressBar pNecesidad;
    private javax.swing.JLabel tEdad;
    // End of variables declaration//GEN-END:variables

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    private void MostrarDiaNoche(JLabel label1, JLabel label2) {
        int tiempo = 1 * 10000;
        Timer timer;
        TimerTask timerTask = new TimerTask() {

            @Override
            public void run() {

                switch (cont) {

                    case 0:
                        cont++;
                        label1.setVisible(true);
                        label2.setVisible(false);
                        contadorDías++;
                        contadorBaño++;
                        contaS++;
                        habilitarBotones(contadorDías);
                        tipoEdad(contadorDías);
                        bajasEnHambre(contaS);
                        irAlBaño(contadorBaño);
                        finDelJuego();
                        
                        

                        break;
                    case 1:
                        cont = 0;
                        label1.setVisible(false);
                        label2.setVisible(true);

                        break;

                }

            }

        };

        timer = new Timer();
        timer.schedule(timerTask, 0, tiempo);
    }

    private void tipoEdad(int contadorDías) {//MUESTRA SI ES HUEVO,JOVEN,ADULTO
        if (contadorDías == 3) {
            this.Huevo.setVisible(false);
            this.Brilo.setVisible(false);
            this.Bebe.setVisible(true);
            this.tEdad.setText(or.EdadMascota(1));
        }

        if (contadorDías == 7) {
            this.Bebe.setVisible(false);
            this.Joven.setVisible(true);
            this.tEdad.setText(or.EdadMascota(3));
        }
        if (contadorDías == 15) {
            this.Joven.setVisible(false);
            this.tEdad.setText(or.EdadMascota(3));
        }
    }

    private void bajasEnHambre(int contador) {
        if (contador == 3) {
            contaS = 0;
            or.setHambre(15);
         
            barrasBar();
            System.out.println(or.getHambre());
            if (or.getHambre() >= 90) {
                JOptionPane.showMessageDialog(rootPane, "Tiene Hambre");
            }

        }

    }
    private void irAlBaño(int conta){
    if (conta==5){
    or.setNecesidad(50);
    or.setAburrimiento(30);
    barrasBar();
    contadorBaño=0;
    if(or.getNecesidad()>0){
    this.btnNecesidad.setVisible(true);
    }
    }
    }

  

    //..................................................
    //BTN Medicamento:
    private void efectoDeMedicamento() {
        if (or.getAburrimiento() <= 20) {
            or.bajarAburrimiento(medi.getAburrimiento());
        }
        if (or.getEnergía() <= 20) {
            or.subirEnergía(medi.getEnergia());
        }
        if (or.getHambre() <= 20) {
            or.quitarHambre(medi.getHambre());
        }
    }

    private void finDelJuego(){
    if (!or.isSalud()){
    this.deshabilitarBotones();
    JOptionPane.showMessageDialog(null, "Tu mascota ha muerto");
    }
    }
    
}
    //TERMINA BTN MEDICAMENTO
